apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:pcXwLw1PzH17uLqCjJxKXddNCFtQq5MkQYv7KRs1W1rvc64r,iv:o7jhvFJ875pRye+be9sRhjpfLjJYvo6hPJgiuUISph0=,tag:FikD+pCU05QETNTghkLVQQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:x6fTuia70MI8i7pn/uNCHLscObO41AyokXkTrObVccyHis/VnGoX2tnfwpToPOuBQZSfP30mIcs+KIe78pVxvWwremSUWTTgLZlyey4WLTvDu45VUe4xm8xkoZM3L+9Mf4V0qY+wd7lsGzTOsR+c0lgMJSjVoXpNdhdm2MQI6cdPxh6mCD/Sk8cz2kOkMCYASMjX8Zi/oS0dbFRN2KZYzG9uBEjghtZpiRp0oEESEw==,iv:V3XUA8W/i1E+/ZlDatGn0CaDwR7oU8FRj9KSXN5si9E=,tag:AQo2jA/ZIjQwYK1/kvRcSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cqd29y9ys8f6k9yqm4hkdcyr9xxvnlyykd22lsk23hf2dayjf4eqtyud74
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6TmR5QytqWXlkUGdrMHNa
            U3QwZzlHOXZ6elJKMmZRcXRxUHlOam1KdFNBCmRGMzZmOEtLV1FvZUtvMjVENzlE
            amVEUldOdEMyRnVlRGdyOHpxZzJ4M0UKLS0tIHFYTVZpMG1xV1ZSMk9Vb1g0MzhU
            QTY1SXhEY3YycXRoTVlBOWtZVm5ZQm8KQmjuTNvfx4yamrCljiz6nNfloxaQiFgG
            C9sMbkEXjYyXjfhqzjfIbLrRU0YRJzzkmyzp6Tk2YjFmzEODsIG+ww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-31T17:02:20Z"
    mac: ENC[AES256_GCM,data:Pgi8H26DYS9A+1x8H5TeamUlkaWzJkSgBpZXSbzKp2Ira+njxip3str/KSUQdvYEkoRpZGwJfLpIDJVnOXyH/qmMwaJe42To9qgqZF+ywNcxQR0/IctMPte29xrpy8yG+GXLPE3yx+y049Wk7ryg9W5DzXgMhKN3Ps0wtOZ3VsI=,iv:N/lQOGEJK+d/EwqXwD/3rY0579OOzcbZkRXtuFJuMQs=,tag:ryLul2bGDALO0djxxuwqtQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
