apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloudflare-secret
stringData:
    api-token: ENC[AES256_GCM,data:fem7AdTlFR3KdiJhZJMdDk04iP/ONSMc/yVLSQhKVFkVRr+58JZKdQ==,iv:hMuUYkFF2Ael5TH3V5smSh9Vu3qO0FZIT0QYcEbA6CA=,tag:UA0rnvMHn8Ozd/1w3ctYmw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cqd29y9ys8f6k9yqm4hkdcyr9xxvnlyykd22lsk23hf2dayjf4eqtyud74
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZm1iU0VKbkZhUEVRQVNz
            dVFSVVN0Q3RvcUxjVFZraWtHbTlhMGlLNlg0ClZyRHNFVExtb0NuZ0hlN2xmNzJj
            QTVmdE5HVmtlKythSFgwUEgvRUpoSVUKLS0tIGNuMlY3SVFwbkdOSlVrK1JjSG1N
            S0g2MHJiNmJrSTczcktKUWVVUW1PY0UKvD2GxZ8m8gRcn04jU0/vfnMjM3xM6g+e
            vBSdFChorS/NoMyQyck4wdiMwrmPg8qI2e/AyF1X6BF3Bln4Zyd/tg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-01T11:41:10Z"
    mac: ENC[AES256_GCM,data:FFz2596D0INqHbS7B0sWYS0NYljxEoZe8UQLATVhd3nokaVFSrYYB4yoYEkAeKWus7UkYuY46bVCVfC9/bnufl4UxfWoSCZRSvN1p8IBr2YJOm2QewDd1Db6vyXEzHmoUHFId0ajGxCOuxYZyNPhWtIfaSDTq5cVr+8WUfykmrU=,iv:ErmZ9nkci4NHrJnjXPgZ5xjjegItCtQ5B3V/r/f+O8s=,tag:a0LyuCjwksijox9FAq3j+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
