apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:cmz+2PIBfF93HzJCwY7Ea5q63jlLcKLjWOAEPWLmwEkY7k3Vspn/ag==,iv:ZwOi7XHJ/Z4O2tO0ogB1jOd29tD+5iDTvRjRvMuZbtk=,tag:fvoPIqL5Q3+Jy663nSPK7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cqd29y9ys8f6k9yqm4hkdcyr9xxvnlyykd22lsk23hf2dayjf4eqtyud74
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEWXJDazJybHdMRXdmcUZQ
            SEJwV0g5NTZ2dWRkSlJoUlpBK0hZQndxSjBRCkE2K1VtQlNRL3Z5MDdzQjFWUGVZ
            a2xsR0krLzFVNkNPWGJ0dnUrekVwcGsKLS0tIFJJWWEvU29xV2dRVnNZd1luWnNl
            blVnd3d6L1RCdHA4MW04dklMV0piZk0Ki036AKi+rlQGeW6uxU9FI2374Sm8fHRm
            hHFxPZifZ8ZxkpIQm15qkiwRgfMcnOAvDqHESp7c9K3COLNVmxzfnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-31T17:02:19Z"
    mac: ENC[AES256_GCM,data:FNuPspASynZH3SPuqwFVK+Sbm3DB2DzyX0FR2lGLGhGEcvas045upQcBTjg9WVuTwsFbcOOZIvisivKxL/Go7K05UhtmIcNfOjhCHnA4rUY6TyuK9CM5W1anOko/ow0z0md38/YddT8FEYsfIepfKP9aHtvr2rzKXpbouWGCXgQ=,iv:lzcOlt6PwIhRyq/BC3Dj6xIQngdcn71348ZiHK5nt9U=,tag:12bg4RSPrbAaCED5etazwA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
