apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:X0f3Czu5Wd+CRsEBRvelAUY9,iv:iAXBUptsoCYnLKj8ZY4teu2s06jAgbYSW7HdWlzLGS0=,tag:RpCccqriNNQ4k4T73SvFfg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:H5g/f7DGiLuMLXrCxZjAJg==,iv:5kswpv9//XJGoxwcXghuY7eVGMlCRPuqOMeyQpo/rJI=,tag:h8wddYBvWJ+rTEbFjjbORQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:26meBAMb17hrBBuOTQgZ2OnsmkEvnGDqqnrHe34aPdEL8VgG,iv:hOlaPHsGDK6/kFTgTAA0rXds0k0GL9zolTgGQol9Rxg=,tag:Ot0AL5wVdLiIOMFtwkq8lw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cqd29y9ys8f6k9yqm4hkdcyr9xxvnlyykd22lsk23hf2dayjf4eqtyud74
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZXZHcFRIQUxKbkdhTTgv
            TS84UXAwTS9VMzg5b3FzMjlBWi9FeEswT2hnCnNmU3lGK3NJdXZIS2ZraTBxTTZQ
            NkpMdC9RaCtPdHhTaS9qdTN6YnB4ZjAKLS0tIFdVSlhYVnUxVmpFb2NzMUJrc3hH
            eVkvYWxkaHZRT0FDbU5iV2NCKy9yL0UKqz5a3O3+cq5dS81xTKeX2SfMrbAP/Zzp
            /R2YXUMTIpuqWt6eI4DNtRmnlhNTTh48jfbiRrqFqh3gOkzLbj/aSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-01T11:41:10Z"
    mac: ENC[AES256_GCM,data:rL6ixwYmkaMa+5G/FTyANbPqlnIT6vNuW0lxeFwJ9GfQN8R6SxI0bZbS+xy1Mx9cMOUwouh5vA3SRo+Xa4lHlDUuAydD1v5kuhp+kByg+eFITpiGha3eilyjv/lCEpCtyfmKB6uWlNZ6MaJ0A0CXraYrRMv9lS/vVkrHbW/jpSc=,iv:2zUOr67FvbQHnoBRjl4ElQhDLIM0QQ1gOGZ3+IYSSVo=,tag:G0K8QCfrl0NKM5vygjSE3g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
