name: kubernetes
description: Create/Update Kubernetes cluster using Pulumi
runtime:
  name: nodejs
  options:
    packagemanager: pnpm
config:
  pulumi:tags:
    value:
      pulumi:template: typescript
